# docker-compose.yml
version: '3.8'

services:
  disa_stig_tool:
    build:
      context: ./tools
      dockerfile: disa_stig_tool.Dockerfile
    ports:
      - "3001:3000"
    volumes:
      - ./artifacts:/app/artifacts
    environment:
      - ARTIFACTS_DIR=/app/artifacts/downloads

  mitre_baseline_tool:
    build:
      context: ./tools
      dockerfile: mitre_baseline_tool.Dockerfile
    ports:
      - "3002:3000"
    volumes:
      - ./artifacts:/app/artifacts
    environment:
      - ARTIFACTS_DIR=/app/artifacts/downloads
      - GITHUB_TOKEN=${GITHUB_TOKEN} # Inject GitHub token for API calls

  # ... Add services for saf_generator_tool, docker_tool, and inspec_runner_tool
  # docker_tool:
  #   ...
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #     - ./artifacts:/app/artifacts
