# docker-compose.yml
version: '3.8'

services:
  disa_stig_tool:
    build:
      context: ./tools
      dockerfile: disa_stig_tool.Dockerfile
    ports:
      - "3001:3000"
    volumes:
      - ./artifacts:/app/artifacts
    environment:
      - ARTIFACTS_DIR=/app/artifacts/downloads

  mitre_baseline_tool:
    build:
      context: ./tools
      dockerfile: mitre_baseline_tool.Dockerfile
    ports:
      - "3002:3000"
    volumes:
      - ./artifacts:/app/artifacts
    environment:
      - ARTIFACTS_DIR=/app/artifacts/downloads
      - GITHUB_TOKEN=${GITHUB_TOKEN} # Inject GitHub token for API calls

  saf_generator_tool:
    build:
      context: ./tools
      dockerfile: saf_generator_tool.Dockerfile
    ports:
      - "3003:3000"
    volumes:
      - ./artifacts:/app/artifacts
    environment:
      - ARTIFACTS_DIR=/app/artifacts/generated

  docker_tool:
    build:
      context: ./tools
      dockerfile: docker_tool.Dockerfile
    ports:
      - "3004:3000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./artifacts:/app/artifacts
    environment:
      - ARTIFACTS_DIR=/app/artifacts/downloads
    privileged: true # Needed for Docker-in-Docker functionality

  inspec_runner_tool:
    build:
      context: ./tools
      dockerfile: inspec_runner_tool.Dockerfile
    ports:
      - "3005:3000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./artifacts:/app/artifacts
    environment:
      - ARTIFACTS_DIR=/app/artifacts/generated
    depends_on:
      - docker_tool
